// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Binding 是绑定到 Wails 前端的服务（适配器模式）。
 * 将内部 Application 的方法适配为前端可调用的格式。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CaptureSelectedScreen 截取选中区域 → OCR → 翻译。
 * @param {number} startX
 * @param {number} startY
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function CaptureSelectedScreen(startX, startY, width, height) {
    return $Call.ByID(3565214714, startX, startY, width, height);
}

/**
 * GetExplainTemplates 获取所有解释模板。
 * @returns {$CancellablePromise<string>}
 */
export function GetExplainTemplates() {
    return $Call.ByID(2033508555);
}

/**
 * GetToolBarPinned 获取工具栏固定状态。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetToolBarPinned() {
    return $Call.ByID(2898495686);
}

/**
 * GetToolbarMode 获取工具栏模式。
 * @returns {$CancellablePromise<string>}
 */
export function GetToolbarMode() {
    return $Call.ByID(792468455);
}

/**
 * GetTranslateMap 获取所有翻译配置。
 * @returns {$CancellablePromise<string>}
 */
export function GetTranslateMap() {
    return $Call.ByID(3187967589);
}

/**
 * GetTranslateWay 获取当前翻译服务。
 * @returns {$CancellablePromise<string>}
 */
export function GetTranslateWay() {
    return $Call.ByID(3373372328);
}

/**
 * Hide 通过名字隐藏窗口。
 * @param {string} windowName
 * @returns {$CancellablePromise<void>}
 */
export function Hide(windowName) {
    return $Call.ByID(3088966351, windowName);
}

/**
 * MyFetch 封装 HTTP 请求（解决前端跨域问题）。
 * @param {string} URL
 * @param {{ [_ in string]?: any }} content
 * @returns {$CancellablePromise<any>}
 */
export function MyFetch(URL, content) {
    return $Call.ByID(193238235, URL, content);
}

/**
 * QueryWord 单词查询：使用 LLM 一次返回音标、词性、释义（中英）、例句（中英）。
 * 结果通过 word_query_result 事件发送（避免 Wails RPC 长时间阻塞）。
 * @param {string} word
 * @returns {$CancellablePromise<void>}
 */
export function QueryWord(word) {
    return $Call.ByID(2160656477, word);
}

/**
 * SetDefaultExplainTemplate 设置默认解释模板。
 * @param {string} templateID
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultExplainTemplate(templateID) {
    return $Call.ByID(1710832067, templateID);
}

/**
 * SetToolBarPinned 设置工具栏固定状态（同时操作窗口置顶）。
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetToolBarPinned(pinned) {
    return $Call.ByID(3011612314, pinned);
}

/**
 * SetTranslateWay 设置当前翻译服务。
 * @param {string} translateWay
 * @returns {$CancellablePromise<void>}
 */
export function SetTranslateWay(translateWay) {
    return $Call.ByID(501931732, translateWay);
}

/**
 * Show 通过名字显示窗口。
 * @param {string} windowName
 * @returns {$CancellablePromise<void>}
 */
export function Show(windowName) {
    return $Call.ByID(2355999858, windowName);
}

/**
 * ToolBarShow 显示工具栏弹窗。
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function ToolBarShow(height) {
    return $Call.ByID(1571489019, height);
}

/**
 * Translate 翻译接口。
 * @param {string} queryText
 * @param {string} fromLang
 * @param {string} toLang
 * @returns {$CancellablePromise<string>}
 */
export function Translate(queryText, fromLang, toLang) {
    return $Call.ByID(1487623407, queryText, fromLang, toLang);
}

/**
 * TranslateMeanings 翻译释义接口。
 * @param {string} queryText
 * @param {string} fromLang
 * @param {string} toLang
 * @returns {$CancellablePromise<string>}
 */
export function TranslateMeanings(queryText, fromLang, toLang) {
    return $Call.ByID(407889959, queryText, fromLang, toLang);
}

/**
 * TranslateStream 流式翻译接口。
 * @param {string} queryText
 * @param {string} fromLang
 * @param {string} toLang
 * @returns {$CancellablePromise<void>}
 */
export function TranslateStream(queryText, fromLang, toLang) {
    return $Call.ByID(311638703, queryText, fromLang, toLang);
}
